# Generated by Django 5.0.4 on 2024-04-26 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 26, 8, 42, 52, 610023)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 26, 8, 42, 52, 610004)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="description_umuti",
            field=models.TextField(
                verbose_name="ukwo bawufata n'ico umaze, bizofasha uwutawuzi"
            ),
        ),
    ]
