# Generated by Django 5.0.4 on 2024-04-26 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0002_alter_umutientree_date_uzohererako_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 26, 8, 44, 27, 596734)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 26, 8, 44, 27, 596679)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="type_umuti",
            field=models.CharField(
                default="null", max_length=10, verbose_name="Flacon, plaquette,"
            ),
        ),
    ]
