# Generated by Django 5.0.4 on 2024-04-27 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0004_umutientree_ratio_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 27, 7, 46, 26, 253227)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 27, 7, 46, 26, 253172)
            ),
        ),
    ]
