# Generated by Django 5.0.4 on 2024-04-27 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0005_alter_umutientree_date_uzohererako_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="umutientree",
            name="code_operation",
            field=models.CharField(default="null", max_length=8),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 27, 7, 46, 57, 765694)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 27, 7, 46, 57, 765590)
            ),
        ),
    ]
