# Generated by Django 5.0.4 on 2024-04-27 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0006_umutientree_code_operation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImitiSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_umuti", models.CharField(default="null", max_length=8)),
                ("name_umuti", models.CharField(default="null", max_length=30)),
                (
                    "description_umuti",
                    models.TextField(
                        verbose_name="ukwo bawufata n'ico umaze, bizofasha uwutawuzi"
                    ),
                ),
                (
                    "type_umuti",
                    models.CharField(
                        default="null",
                        max_length=10,
                        verbose_name="Ni Flacon canke plaquette,",
                    ),
                ),
                ("type_in", models.CharField(default="null", max_length=10)),
                ("ratio_type", models.FloatField(default=1)),
                ("type_out", models.CharField(default="null", max_length=10)),
                ("price_in", models.IntegerField(default=0)),
                ("price_out", models.IntegerField(default=0)),
                ("difference", models.IntegerField(default=0)),
                ("quantite_restant", models.IntegerField(default=0)),
                ("location", models.CharField(default="null", max_length=10)),
                ("lot", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 27, 8, 29, 29, 310337)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 27, 8, 29, 29, 310283)
            ),
        ),
    ]
