# Generated by Django 5.0.4 on 2024-04-29 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0007_imitiset_alter_umutientree_date_uzohererako_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UmutiSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_umuti", models.CharField(default="null", max_length=8)),
                ("name_umuti", models.CharField(default="null", max_length=30)),
                ("quantity", models.IntegerField(default=1)),
                ("price_out", models.IntegerField(default=0)),
                ("difference", models.IntegerField(default=0)),
                (
                    "code_operation_entrant",
                    models.CharField(default="null", max_length=8),
                ),
                ("code_operation", models.CharField(default="null", max_length=8)),
                ("operator", models.CharField(default="null", max_length=15)),
                (
                    "date_operation",
                    models.DateField(
                        default=datetime.datetime(2024, 4, 29, 14, 0, 42, 36945)
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="umutientree",
            name="quantite_init",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 29, 14, 0, 42, 34318)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 29, 14, 0, 42, 34251)
            ),
        ),
    ]
