# Generated by Django 5.0.4 on 2024-04-30 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0010_alter_umutientree_date_uzohererako_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 11, 9, 11, 538742)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 30, 11, 9, 11, 538627)
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 30, 11, 9, 11, 541368, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
