# Generated by Django 5.0.4 on 2024-05-01 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0011_alter_umutientree_date_uzohererako_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 1, 13, 13, 3, 496811)
            ),
        ),
        migrations.AddField(
            model_name="imitiset",
            name="qte_entrant_big",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 1, 13, 13, 3, 495032)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 1, 13, 13, 3, 494968)
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 1, 13, 13, 3, 497807, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
