# Generated by Django 5.0.4 on 2024-05-03 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0015_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="umutiReportSell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_umuti", models.CharField(default="null", max_length=8)),
                ("name_umuti", models.CharField(default="null", max_length=30)),
                ("nb_vente", models.IntegerField(default=0)),
                ("px_T_vente", models.IntegerField(default=0)),
                ("benefice", models.IntegerField(default=0)),
                ("nb_rest", models.IntegerField(default=0)),
                ("px_T_rest", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 13, 17, 28, 797200, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 5, 3, 13, 17, 28, 795462)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 13, 17, 28, 795351, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 3, 13, 17, 28, 798237, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
