# Generated by Django 5.0.4 on 2024-06-06 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0017_umutisold_price_in_umutisold_price_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imitiset",
            name="checked_imiti",
            field=models.TextField(default="e"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 6, 16, 54, 13, 753800, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 6, 16, 54, 13, 752216)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 6, 16, 54, 13, 752163, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 6, 16, 54, 13, 755100, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
