# Generated by Django 5.0.4 on 2024-06-07 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0018_imitiset_checked_imiti_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imitiset",
            name="checked_qte",
            field=models.TextField(default="o"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 7, 7, 42, 21, 415187, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 7, 7, 42, 21, 414685)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 7, 7, 42, 21, 414666, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 7, 7, 42, 21, 415548, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
