# Generated by Django 5.0.4 on 2024-06-28 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0020_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 9, 57, 28, 946865, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 28, 9, 57, 28, 943994)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 9, 57, 28, 943917, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="code_operation",
            field=models.CharField(default="null", max_length=12),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="code_operation_entrant",
            field=models.CharField(default="null", max_length=12),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 9, 57, 28, 948778, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
