# Generated by Django 5.0.4 on 2024-06-28 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0021_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="imitiSuggest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_umuti", models.CharField(default="null", max_length=8)),
                ("name_umuti", models.CharField(default="null", max_length=30)),
                ("qte", models.IntegerField(default=0)),
                ("p_achat", models.IntegerField(default=0)),
                ("p_vente", models.IntegerField(default=0)),
                ("benefice", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 11, 8, 47, 150860, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 6, 28, 11, 8, 47, 149350)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 11, 8, 47, 149295, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 28, 11, 8, 47, 151935, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
