# Generated by Django 5.0.4 on 2024-07-05 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0025_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UmutiEntreeBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_winjiriyeko",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 7, 5, 7, 24, 53, 225069, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "date_uzohererako",
                    models.DateField(
                        default=datetime.datetime(2024, 7, 5, 7, 24, 53, 225143)
                    ),
                ),
                ("code_umuti", models.CharField(default="null", max_length=8)),
                ("name_umuti", models.CharField(default="null", max_length=30)),
                (
                    "description_umuti",
                    models.TextField(
                        verbose_name="ukwo bawufata n'ico umaze, bizofasha uwutawuzi"
                    ),
                ),
                (
                    "type_umuti",
                    models.CharField(
                        default="null",
                        max_length=10,
                        verbose_name="Ni Flacon canke plaquette,",
                    ),
                ),
                ("type_in", models.CharField(default="null", max_length=10)),
                ("ratio_type", models.FloatField(default=1)),
                ("type_out", models.CharField(default="null", max_length=10)),
                ("price_in", models.IntegerField(default=0)),
                ("price_out", models.IntegerField(default=0)),
                ("difference", models.IntegerField(default=0)),
                ("quantite_initial", models.IntegerField(default=0)),
                ("quantite_restant", models.IntegerField(default=0)),
                ("location", models.CharField(default="null", max_length=10)),
                ("code_operation", models.CharField(default="null", max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 7, 24, 53, 226761, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 7, 24, 53, 229493, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 5, 7, 24, 53, 223069)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 7, 24, 53, 223018, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 7, 24, 53, 227997, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
