# Generated by Django 5.0.4 on 2024-07-05 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0026_umutientreebackup_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="umutientree",
            name="operator",
            field=models.CharField(default="null", max_length=15),
        ),
        migrations.AddField(
            model_name="umutientreebackup",
            name="operator",
            field=models.CharField(default="null", max_length=15),
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 8, 28, 2, 776866, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 8, 28, 2, 777788, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 5, 8, 28, 2, 775906)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 8, 28, 2, 775884, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 5, 8, 28, 2, 776362)
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 8, 28, 2, 776347, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 5, 8, 28, 2, 777284, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
