# Generated by Django 5.0.4 on 2024-07-22 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0027_umutientree_operator_umutientreebackup_operator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsdToBif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actualExchangeRate", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="umutientree",
            name="price_in_usd",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="umutientree",
            name="price_out_usd",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="umutientreebackup",
            name="price_in_usd",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="umutientreebackup",
            name="price_out_usd",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 22, 6, 13, 3, 902593, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 22, 6, 13, 3, 904985, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 22, 6, 13, 3, 899343)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 22, 6, 13, 3, 899252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 7, 22, 6, 13, 3, 900890)
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 22, 6, 13, 3, 900843, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 22, 6, 13, 3, 903593, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
