# Generated by Django 5.0.4 on 2024-12-13 10:26

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0038_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="null", max_length=25)),
                ("rate_assure", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 10, 26, 49, 438848, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 10, 26, 49, 441509, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 13, 10, 26, 49, 436070)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 10, 26, 49, 436014, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 13, 10, 26, 49, 437379)
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 10, 26, 49, 437334, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 10, 26, 49, 440086, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usdtobif",
            name="effect_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 10, 26, 49, 442171, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="BonDeCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beneficiaire", models.CharField(default="inconnu", max_length=25)),
                ("num_beneficiaire", models.CharField(default="0000", max_length=10)),
                ("num_du_bon", models.CharField(default="0000", max_length=10)),
                ("date_du_bon", models.DateField(default=django.utils.timezone.now)),
                ("date_served", models.DateField(default=django.utils.timezone.now)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharma.assurance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="inconnu", max_length=25)),
                ("phone_number", models.CharField(default="1111", max_length=12)),
                (
                    "date_bon",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date yatangiweko",
                    ),
                ),
                (
                    "assureur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharma.assurance",
                    ),
                ),
            ],
        ),
    ]
