# Generated by Django 5.0.4 on 2024-12-13 14:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0039_assurance_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="umutisold",
            name="bon_de_commande",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="pharma.bondecommande",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assurance",
            name="rate_assure",
            field=models.SmallIntegerField(
                default=0, verbose_name="Le Taux d'assurer le Malade"
            ),
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 14, 17, 29, 41902, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 14, 17, 29, 43397, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 13, 14, 17, 29, 40634)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 14, 17, 29, 40602, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 13, 14, 17, 29, 41267)
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 14, 17, 29, 41252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 14, 17, 29, 42809, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usdtobif",
            name="effect_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 13, 14, 17, 29, 43695, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
