# Generated by Django 5.0.4 on 2024-12-14 09:13

import datetime
import django.db.models.deletion
import pharma.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0048_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondecommande",
            name="montant_caisse",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 14, 9, 13, 36, 998135, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 14, 9, 13, 36, 999625, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 14, 9, 13, 36, 996869)
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 14, 9, 13, 36, 996837, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_uzohererako",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 14, 9, 13, 36, 997503)
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_winjiriyeko",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 14, 9, 13, 36, 997485, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="bon_de_commande",
            field=models.ForeignKey(
                default=pharma.models.getBonDeCommandeInstance,
                on_delete=django.db.models.deletion.CASCADE,
                to="pharma.bondecommande",
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 14, 9, 13, 36, 999058, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usdtobif",
            name="effect_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 14, 9, 13, 36, 999917, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
