# Generated by Django 5.0.4 on 2024-12-24 11:50

import datetime
import django.db.models.deletion
import pharma.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0056_alter_bondecommande_num_du_bon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondecommande",
            name="organization",
            field=models.ForeignKey(
                default=pharma.models.getAssuranceInstance,
                on_delete=django.db.models.deletion.CASCADE,
                to="pharma.assurance",
            ),
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 24, 11, 50, 15, 469397, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 24, 11, 50, 15, 473779, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 24, 11, 50, 15, 466115, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 24, 11, 50, 15, 466169)
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 24, 11, 50, 15, 467508, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 24, 11, 50, 15, 467563)
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 24, 11, 50, 15, 472152, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usdtobif",
            name="effect_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 24, 11, 50, 15, 474669, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
