# Generated by Django 5.0.4 on 2024-12-25 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0059_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imitiset",
            name="description_umuti",
        ),
        migrations.AddField(
            model_name="imitiset",
            name="classe_med",
            field=models.CharField(default="null", max_length=30),
        ),
        migrations.AddField(
            model_name="imitiset",
            name="sous_classe_med",
            field=models.CharField(default="null", max_length=30),
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 456830, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 461206, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 453568, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 453625, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 454998, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 455043, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 459476, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usdtobif",
            name="effect_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 12, 25, 8, 3, 5, 462029, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
