# Generated by Django 5.0.4 on 2025-01-06 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0062_classthep_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classthep",
            name="name",
            field=models.CharField(default="inconnu", max_length=35),
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 264590, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 266086, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subclassthep",
            name="name",
            field=models.CharField(default="inconnu", max_length=40),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 263469, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 263490, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 263958, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 263975, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 265521, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usdtobif",
            name="effect_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 6, 14, 28, 53, 266390, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
