# Generated by Django 5.0.4 on 2025-01-08 18:21

import datetime
import django.db.models.deletion
import pharma.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0064_alter_classthep_name_alter_imitiset_date_last_vente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_adherant", models.CharField(default="adhe", max_length=25)),
                ("employeur", models.CharField(default="empl", max_length=25)),
                ("beneficiaire", models.CharField(default="inconnu", max_length=25)),
                ("relation", models.CharField(default="lui-meme", max_length=10)),
                (
                    "joined_on",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 1, 8, 18, 21, 10, 634196, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="imitiset",
            name="date_last_vente",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 632593, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="imitisuggest",
            name="previous_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 639655, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 628771, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientree",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 628882, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_entrant",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 630778, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutientreebackup",
            name="date_peremption",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 630822, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="date_operation",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 638045, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="usdtobif",
            name="effect_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 8, 18, 21, 10, 640337, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="BonDeCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meds", models.TextField()),
                ("cout", models.IntegerField(default=0)),
                ("assu_rate", models.IntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                ("date_paid", models.DateField(blank=True)),
                ("date_prescri", models.DateField(blank=True)),
                (
                    "date_served",
                    models.DateField(
                        default=datetime.datetime(
                            2025, 1, 8, 18, 21, 10, 635701, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=pharma.models.getAssuranceInstance,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharma.assurance",
                    ),
                ),
                (
                    "beneficaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pharma.client"
                    ),
                ),
            ],
        ),
    ]
