# Generated by Django 5.0.4 on 2025-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0066_alter_bondecommand_date_served_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="numero_carte",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="nom_adherant",
            field=models.CharField(default="adhe", max_length=25, unique=True),
        ),
    ]
