# Generated by Django 5.0.4 on 2025-01-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0067_client_numero_carte_alter_client_nom_adherant"),
    ]

    operations = [
        migrations.AddField(
            model_name="assurance",
            name="dette",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(blank=True, default=0.0004938271604938272),
            preserve_default=False,
        ),
    ]
