# Generated by Django 5.0.4 on 2025-01-14 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0068_assurance_dette"),
    ]

    operations = [
        migrations.AddField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 4, 16, 45, 2, 121007, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
