# Generated by Django 5.0.4 on 2025-01-15 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0069_assurance_last_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommand",
            name="num_carte",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 5, 3, 52, 9, 694113, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
