# Generated by Django 5.0.4 on 2025-01-16 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0070_bondecommand_num_carte_alter_assurance_last_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bondecommand",
            old_name="num_carte",
            new_name="num_bon",
        ),
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 3, 33, 49, 318210, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
