# Generated by Django 5.0.4 on 2025-01-16 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0071_rename_num_carte_bondecommand_num_bon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommand",
            name="categorie",
            field=models.CharField(default="null", max_length=4),
        ),
        migrations.AddField(
            model_name="bondecommand",
            name="montant_dette",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 3, 41, 15, 170265, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
