# Generated by Django 5.0.4 on 2025-01-16 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0072_bondecommand_categorie_bondecommand_montant_dette_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 3, 43, 15, 147618, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="beneficiaire",
            field=models.CharField(default="inconnu", max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="nom_adherant",
            field=models.CharField(default="adhe", max_length=25),
        ),
    ]
