# Generated by Django 5.0.4 on 2025-01-16 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0073_alter_assurance_last_paid_alter_client_beneficiaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 10, 0, 59, 997635, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="assurance",
            name="name",
            field=models.CharField(default="null", max_length=25, unique=True),
        ),
    ]
