# Generated by Django 5.0.4 on 2025-01-16 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0077_rename_beneficaire_bondecommand_beneficiaire_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bondecommand",
            old_name="beneficiaire",
            new_name="beneficaire",
        ),
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 10, 35, 32, 738854, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 10, 35, 32, 738854, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_prescri",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 10, 35, 32, 738854, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
