# Generated by Django 5.0.4 on 2025-01-16 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0078_rename_beneficiaire_bondecommand_beneficaire_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bondecommand",
            old_name="beneficaire",
            new_name="beneficiaire",
        ),
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 10, 37, 19, 770675, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 10, 37, 19, 770675, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_prescri",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 10, 37, 19, 770675, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
