# Generated by Django 5.0.4 on 2025-01-16 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0079_rename_beneficaire_bondecommand_beneficiaire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 18, 33, 34, 423352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 18, 33, 34, 423352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_prescri",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 6, 18, 33, 34, 423352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="num_bon",
            field=models.CharField(default="null", max_length=12),
        ),
    ]
