# Generated by Django 5.0.4 on 2025-01-17 09:34

import datetime
import django.db.models.deletion
import pharma.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0080_alter_assurance_last_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 7, 9, 33, 59, 829965, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 7, 9, 33, 59, 829965, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_prescri",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 7, 9, 33, 59, 829965, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="umutisold",
            name="bon_de_commande",
            field=models.ForeignKey(
                default=pharma.models.getBonDeCommandeInstance,
                on_delete=django.db.models.deletion.CASCADE,
                to="pharma.bondecommand",
            ),
        ),
    ]
