# Generated by Django 5.0.4 on 2025-01-19 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0081_alter_assurance_last_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imitiset",
            name="forme",
            field=models.CharField(default="null", max_length=8),
        ),
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 9, 5, 21, 24, 861110, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 9, 5, 21, 24, 861110, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_prescri",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 2, 9, 5, 21, 24, 861110, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
