# Generated by Django 5.0.4 on 2025-03-20 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharma", "0085_beneficeprogram_alter_assurance_last_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondecommand",
            name="total",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assurance",
            name="last_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 4, 10, 10, 22, 45, 56573, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_paid",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 4, 10, 10, 22, 45, 56573, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="bondecommand",
            name="date_prescri",
            field=models.DateField(
                default=datetime.datetime(
                    1882, 4, 10, 10, 22, 45, 56573, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
